## Isolation Forest

Возвращает оценку аномалии каждой выборки с помощью алгоритма IsolationForest

In [129]:
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MaxAbsScaler,Normalizer,StandardScaler
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn import metrics
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM

In [130]:
RANDOM_STATE = 42
sns.set(style="darkgrid")
pd.set_option('display.max_rows', 1000)

In [139]:
# Может запилить GridSearch для поиска оптим.гиперпараметров?

outliers_fraction = 0.07 #регулируем    0.07 
data = pd.read_csv("all_eda_obr20_04-2.csv")

data1 =  data[data['RIG_STATE']==7]
df2 = data1[['DEPT_bin', 'SPPA_bin', 'BVEL_bin', 'HKLD_bin', 'BPOS_bin']]
df6 = data1[['DEPT_bin', 'SPPA_bin', 'BVEL_bin', 'HKLD_bin', 
            'BPOS_bin', "RPM_bin", "STOR_bin"]]
#df2 = data1[[ 'HKLD', 'STOR','FLWI', 'RPM', 'SPPA', 'ECD']]
#pca = PCA(n_components=2)
#df2 = pca.fit_transform(df2)
model =  IsolationForest(n_estimators=90, 
                         max_samples = 100,#регулируем
                        contamination = outliers_fraction)
model.fit(df2)
labels = model.predict(df2)
labels
#clf = IsolationForest(random_state=0).fit(df2)
#labels = clf.predict(df2)

array([ 1,  1,  1, ..., -1, -1, -1])

In [141]:
df9 = pd.DataFrame()
df9['StuckPipe'] = data1['StuckPipe']
df9['predict'] = labels
df9.value_counts()

StuckPipe  predict
0.0         1         9848
           -1          376
1.0        -1          277
            1          168
dtype: int64

In [142]:
df9['predict'].unique()

array([ 1, -1])

In [143]:
df9['predict']=df9['predict'].apply(lambda n: 0 if n==1 else 1)
df9['predict'].value_counts()

0    10016
1      653
Name: predict, dtype: int64

In [144]:
df9.value_counts()

StuckPipe  predict
0.0        0          9848
           1           376
1.0        1           277
           0           168
dtype: int64

In [145]:
metrics.f1_score(data1['StuckPipe'], df9['predict'])

0.5045537340619308

## Проверим модель на 1 скважине: (получается лучше результат на отдельных скважинах)

In [378]:
outliers_fraction = 0.09 #регулируем    0.07 
data = pd.read_csv("all_eda_obr20_04-2.csv")

data1 =  data[data['RIG_STATE']==7]
data1 =  data1[data1['hole']=="241"]   # 241
df2 = data1[['DEPT_bin', 'SPPA_bin', 'BVEL_bin', 'HKLD_bin', 'BPOS_bin']]
df77 = data1[[ 'DEPT_bin','SPPA_bin',  'HKLD_bin',
            'BPOS_bin', "RPM_bin",'DEPT_bin',
            ]] #"STOR_bin",'BPOS_bin', "RPM_bin"

#pca = PCA(n_components=2)
#df2 = pca.fit_transform(df2)
model =  IsolationForest(n_estimators=8, 
                         max_samples = 50,#регулируем
                        contamination = outliers_fraction)
model.fit(df2)
labels = model.predict(df2)
labels

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [379]:
df9 = pd.DataFrame()
df9['StuckPipe'] = data1['StuckPipe']
df9['predict'] = labels
df9.value_counts()

StuckPipe  predict
0.0         1         480
           -1          25
1.0        -1          23
            1           1
dtype: int64

In [380]:
df9['predict']=df9['predict'].apply(lambda n: 0 if n==1 else 1)
df9['predict'].value_counts()

0    481
1     48
Name: predict, dtype: int64

In [381]:
metrics.f1_score(data1['StuckPipe'], df9['predict'])

0.638888888888889

In [382]:
data.hole.unique()

array(['204', '210ST', '210ST2', '216', '217ST1', '217ST2', '220',
       '220ST3', '220ST4', '234ST2', '241', '243', '256ST2', '256ST3',
       '278', '279'], dtype=object)

In [372]:
outliers_fraction = 0.09 #регулируем    0.07 , 0.09
data = pd.read_csv("all_eda_obr20_04-2.csv")

data1 =  data[data['RIG_STATE']==7]
data1 =  data1[data1['hole']=="241"]   # 241             
df2 = data1[['DEPT_bin', 'SPPA_bin', 'BVEL_bin', 'HKLD_bin', 'BPOS_bin']]
df77 = data1[[ 'DEPT_bin','SPPA_bin',  'HKLD_bin',
            'BPOS_bin', "RPM_bin",'DEPT_bin'
            ]] 
#pca = PCA(n_components=2)
#df2 = pca.fit_transform(df2)
model =  IsolationForest(n_estimators=10,  # регулируем  15
                          max_samples = 20, # регулируем  90
                        contamination = outliers_fraction)
model.fit(df2)
labels = model.predict(df2)
labels

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [373]:
df9 = pd.DataFrame()
df9['StuckPipe'] = data1['StuckPipe']
df9['predict'] = labels
df9.value_counts()

StuckPipe  predict
0.0         1         482
           -1          23
1.0        -1          23
            1           1
dtype: int64

In [348]:
df9['predict']=df9['predict'].apply(lambda n: 0 if n==1 else 1)
df9['predict'].value_counts()

0    483
1     46
Name: predict, dtype: int64

In [350]:
df9.value_counts()

StuckPipe  predict
0.0        0          482
           1           23
1.0        1           23
           0            1
dtype: int64

In [349]:
metrics.f1_score(data1['StuckPipe'], df9['predict'])

0.6571428571428571